### ISSUE TITLE
Loading page jitter

### ISSUE THREAD

**Issue by jeremybull** [jhoguet/loading-page#1]
The loading page jitters -- appears to jump around by a few pixels -- during loading. It may be related to scroll bars appearing and disappearing. Observed on Chrome on Mac.

Screen recording: https://goo.gl/ia902F

**Comment by jhoguet** [comment]
I wasn't able to reproduce this at first... turned out mac does a great job of masking these types of issues by default... Once I enabled scroll bars permanently... then I could reproduce 

http://kb.tableau.com/articles/knowledgebase/displaying-scroll-bar

![image](https://cloud.githubusercontent.com/assets/1234146/14413633/ed11b378-ff4d-11e5-8e8a-7ffb6b1233f5.png)

**Comment by jhoguet** [comment]
hmmm... I am not sure how best to solve this. 

I can think of a couple options. 

1) instead of centering the content using percents... I could center it with pixels
- harder to center
- harder to make responsive
2) I prevent the scroll bar from showing up on the page... until after done loading is called
 - requires me to be more invasive on the host page
3) instead of making the scrollable area be the body (which includes the iframe) we could make the scrollable area be some content the host owns
 - forces the host to not have a scrollable body...

**Comment by jhoguet** [comment]
option 3 seems to be working well, going update the readme with this advice
